import json
import os
import sqlite3
import sys


def detect_and_parse_json(value):
    """Try to parse a value as JSON if it looks like JSON."""
    if value is None or not isinstance(value, str):
        return value
    
    stripped = value.strip()
    if not (stripped.startswith('{') or stripped.startswith('[')):
        return value
    
    try:
        return json.loads(value)
    except (json.JSONDecodeError, ValueError):
        return value


def export_table_to_jsx(conn, table_name, output_dir):
    """Export a single table to a JSX file."""
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name}")
    
    rows = cursor.fetchall()
    if not rows:
        print(f"  ⚠ {table_name}: empty table, skipping")
        return
    
    data = []
    for row in rows:
        row_dict = dict(row)
        parsed_row = {k: detect_and_parse_json(v) for k, v in row_dict.items()}
        data.append(parsed_row)
    var_name = table_name.replace('-', '_').replace(' ', '_')
    filename = f"{table_name}_dump.jsx"
    
    js_content = json.dumps(data, indent=2, ensure_ascii=False)
    
    jsx_content = f"""// Auto-generated dump from '{table_name}' table - DO NOT EDIT
// Generated by export.py

export const {var_name} = {js_content};
"""
    
    # Write file
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, filename)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(jsx_content)
    
    print(f"  ✓ {table_name}: {len(data)} rows → {filename}")


def get_all_tables(conn):
    """Get all table names from the database."""
    cursor = conn.cursor()
    cursor.execute("""
        SELECT name FROM sqlite_master 
        WHERE type='table' 
        AND name NOT LIKE 'sqlite_%'
        ORDER BY name
    """)
    return [row[0] for row in cursor.fetchall()]


def main():
    # Parse arguments
    if len(sys.argv) > 1:
        db_path = sys.argv[1]
    else:
        path = os.path.dirname(os.path.abspath(__file__))
        graph_db_path = os.path.join(path, "..", "graph.db")
        db_path = os.path.abspath(graph_db_path)
    
    if len(sys.argv) > 2:
        output_dir = sys.argv[2]
    else:
        output_dir = os.path.join(path, "data")

    # Check if database exists
    if not os.path.exists(db_path):
        print(f"❌ Error: Database not found: {db_path}")
        sys.exit(1)
    
    print(f"📊 Exporting database: {db_path}")
    print(f"📁 Output directory: {output_dir}")
    print()
    
    # Connect to database
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    
    try:
        # Get all tables
        tables = get_all_tables(conn)
        
        if not tables:
            print("⚠ No tables found in database")
            return
        
        print(f"Found {len(tables)} table(s):")
        print()
        
        # Export each table
        for table in tables:
            export_table_to_jsx(conn, table, output_dir)
        
        print()
        print(f"✅ Successfully exported {len(tables)} table(s) to JSX dumps")
        
    finally:
        conn.close()


if __name__ == "__main__":
    main()